services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./storage/mongodb:/data/db
    networks:
      - randovango
  db_randovango:
    image: mysql
    container_name: db_randovango
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PSWD}
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    networks:
      - randovango
  
  adminer:
    image: adminer
    container_name: adminer_randovango
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - randovango

networks:
  randovango:
    driver: bridge