SELECT ?item ?itemLabel ?coord ?title ?image WHERE {
  ?commune rdfs:label "Plougonvelin"@fr ; wdt:P625 ?center .
  SERVICE wikibase:around {
    ?item wdt:P625 ?coord .
    bd:serviceParam wikibase:center ?center ;
                    wikibase:radius "8" .
  }
  OPTIONAL { ?item wdt:P18 ?image. }
  ?article schema:about ?item ;
           schema:inLanguage "fr" ;
           schema:isPartOf <https://fr.wikipedia.org/> ;
           schema:name ?title .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "fr". }
}
LIMIT 100
